---
author: "Suresh Gopalakrishnan"
code_folding: hide
date: "January 25, 2018"
linkcolor: cyan
number_sections: yes
output:
  pdf_document: default
  html_document: default
theme: cosmo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##  Data Wrangling Exercise 1: Basic Data Manipulation
Suresh
Date- `r Sys.Date()` 

#### Load required packages 
```{r message=FALSE,warning=FALSE}
library(dplyr) # DW pkg
library(tidyr) # DW pkg
library(data.table) # Base pkg for DescTools
library(DescTools) # For LIKE and ANY function
library(readr) # write faster csv files
```

#### Read input file *"refine_original.csv"*

```{r message=FALSE,warning=FALSE}
orginal <- read.csv("refine_original.csv")
glimpse(orginal)
orginal <- data.frame(orginal)
```

#### Clean up brand names

```{r message=FALSE,warning=FALSE}
comp1 <- orginal$company

for (i in seq(length(comp1)))
{
  tolower(comp1[i])
  if (comp1[i] %like any% c("%li%", "p%", "f%", "%ps")) {
    comp1[i] <- "phillips"
  } else if (comp1[i] %like% "ak%") {
    comp1[i] <- "akzo"
  } else if (comp1[i] %like% "van%") {
    comp1[i] <- "van houten"
  } else if (comp1[i] %like% "un%") {
    comp1[i] <- "unilever"
  }
}
orginal$company <- comp1
```

#### Function to name product_catetory
```{r message=FALSE,warning=FALSE}
fetch <- function(x) {
  ifelse(x == "p", "Smartphone",
    ifelse(x == "v", "TV",
      ifelse(x == "x", "Laptop",
        ifelse(x == "q", "Tablet", NA)
      )
    )
  )
}
```

#### Edit rest of columns 
```{r message=FALSE,warning=FALSE}
clean <- orginal %>%
  separate(Product.code...number, c("product_code", "product_number"), "-") %>%
  mutate(company = tolower(company)) %>%
  mutate(product_category = fetch(product_code)) %>%
  unite(full_address, address, city, country, sep = ", ") %>%
  mutate(company_philips = ifelse(company == "phillips", 1, 0)) %>%
  mutate(company_akzo = ifelse(company == "akzo", 1, 0)) %>%
  mutate(company_van_houten = ifelse(company == "van houten", 1, 0)) %>%
  mutate(company_unilever = ifelse(company == "unilever", 1, 0)) %>%
  mutate(product_smartphone = ifelse(product_code == "p", 1, 0)) %>%
  mutate(product_tv = ifelse(product_code == "v", 1, 0)) %>%
  mutate(product_laptop = ifelse(product_code == "x", 1, 0)) %>%
  mutate(product_tablet = ifelse(product_code == "q", 1, 0))
glimpse(clean)
```

#### Write output to final file 

```{r message=FALSE,warning=FALSE}
clean %>% write_csv("refine_clean.csv")
```

